apiVersion: v1
kind: Service
metadata:
  name: service-b
  namespace: default
  labels:
    app: service-b
spec:
  selector:
    app: service-b
  ports:
    - name: http
      port: 3000
      targetPort: 3000
    - name: metrics
      port: 9100
      targetPort: 9100